changelog:
  categories:
    - title: Breaking Changes
      labels:
        - breaking-change
    - title: Added
      labels:
        - enhancement
    - title: Fixed
      labels:
        - bug
    - title: Removed
      labels:
        - deprecated
    - title: Dependencies
      labels:
        - dependencies
    - title: Other Changes
      labels:
        - "*"
